import type { Bank, BlogPost, Promotion, Tariff } from "./types";

export const banks: Bank[] = [
	{
		id: "tinkoff",
		name: "Тинькофф Банк",
		logo: "/tinkoff-bank-logo-yellow.jpg",
		description: "Онлайн-банк для бизнеса с быстрым открытием счёта",
		rating: 4.8,
		tariffCount: 3,
		minPrice: 0,
		hasOnlineOpening: true,
		hasFreeTariff: true,
		regions: ["Москва", "Санкт-Петербург", "Все регионы"],
	},
	{
		id: "sber",
		name: "Сбербанк",
		logo: "/sberbank-logo-green.jpg",
		description: "Крупнейший банк России с широкой сетью отделений",
		rating: 4.5,
		tariffCount: 4,
		minPrice: 0,
		hasOnlineOpening: true,
		hasFreeTariff: true,
		regions: ["Москва", "Санкт-Петербург", "Все регионы"],
	},
	{
		id: "alfa",
		name: "Альфа-Банк",
		logo: "/alfa-bank-logo-red.jpg",
		description: "Надёжный банк с выгодными условиями для бизнеса",
		rating: 4.6,
		tariffCount: 3,
		minPrice: 0,
		hasOnlineOpening: true,
		hasFreeTariff: true,
		regions: ["Москва", "Санкт-Петербург", "Все регионы"],
	},
	{
		id: "vtb",
		name: "ВТБ",
		logo: "/vtb-bank-logo-blue.jpg",
		description: "Государственный банк с гибкими тарифами",
		rating: 4.4,
		tariffCount: 3,
		minPrice: 0,
		hasOnlineOpening: true,
		hasFreeTariff: false,
		regions: ["Москва", "Санкт-Петербург", "Все регионы"],
	},
	{
		id: "raiffeisen",
		name: "Райффайзенбанк",
		logo: "/raiffeisen-bank-logo-yellow-black.jpg",
		description: "Международный банк с качественным сервисом",
		rating: 4.7,
		tariffCount: 2,
		minPrice: 490,
		hasOnlineOpening: true,
		hasFreeTariff: false,
		regions: ["Москва", "Санкт-Петербург", "Екатеринбург"],
	},
	{
		id: "otkritie",
		name: "Открытие",
		logo: "/otkritie-bank-logo-blue.jpg",
		description: "Универсальный банк для малого бизнеса",
		rating: 4.3,
		tariffCount: 3,
		minPrice: 0,
		hasOnlineOpening: true,
		hasFreeTariff: true,
		regions: ["Москва", "Санкт-Петербург", "Все регионы"],
	},
	{
		id: "modul",
		name: "Модульбанк",
		logo: "/modulbank-logo-green.jpg",
		description: "Банк для предпринимателей с простым интерфейсом",
		rating: 4.6,
		tariffCount: 3,
		minPrice: 0,
		hasOnlineOpening: true,
		hasFreeTariff: true,
		regions: ["Москва", "Санкт-Петербург", "Все регионы"],
	},
	{
		id: "tochka",
		name: "Точка",
		logo: "/tochka-bank-logo-blue.jpg",
		description: "Цифровой банк с инновационными решениями",
		rating: 4.7,
		tariffCount: 2,
		minPrice: 0,
		hasOnlineOpening: true,
		hasFreeTariff: true,
		regions: ["Москва", "Санкт-Петербург", "Все регионы"],
	},
];

export const tariffs: Tariff[] = [
	// Тинькофф
	{
		id: "tinkoff-simple",
		bankId: "tinkoff",
		bankName: "Тинькофф Банк",
		bankLogo: "/tinkoff-bank-logo-yellow.jpg",
		name: "Простой",
		price: 0,
		priceLabel: "Бесплатно",
		description: "Базовый тариф для начинающего бизнеса",
		targetAudience: "ИП с небольшим оборотом до 500 000 ₽",
		operationsLimit: 10,
		transferCommission: "49 ₽ за платёж",
		cashWithdrawalCommission: "1.5% + 99 ₽",
		freeTransfers: 3,
		features: [
			"Бесплатное обслуживание",
			"3 бесплатных платежа",
			"Мобильное приложение",
			"Круглосуточная поддержка",
		],
		requirements: ["Паспорт", "ИНН", "ОГРНИП"],
		isRecommended: true,
		recommendationReason: "Лучший выбор для старта бизнеса",
	},
	{
		id: "tinkoff-advanced",
		bankId: "tinkoff",
		bankName: "Тинькофф Банк",
		bankLogo: "/tinkoff-bank-logo-yellow.jpg",
		name: "Продвинутый",
		price: 1990,
		priceLabel: "1 990 ₽/мес",
		description: "Для активного бизнеса с большим количеством операций",
		targetAudience: "ИП и ООО с оборотом до 2 000 000 ₽",
		operationsLimit: 50,
		transferCommission: "29 ₽ за платёж",
		cashWithdrawalCommission: "1% + 79 ₽",
		freeTransfers: 20,
		features: [
			"20 бесплатных платежей",
			"Сниженные комиссии",
			"Бизнес-карта",
			"Кэшбэк до 5%",
		],
		requirements: ["Паспорт", "ИНН", "ОГРН"],
	},
	{
		id: "tinkoff-professional",
		bankId: "tinkoff",
		bankName: "Тинькофф Банк",
		bankLogo: "/tinkoff-bank-logo-yellow.jpg",
		name: "Профессиональный",
		price: 4990,
		priceLabel: "4 990 ₽/мес",
		description: "Максимум возможностей для крупного бизнеса",
		targetAudience: "ООО с оборотом от 5 000 000 ₽",
		operationsLimit: 200,
		transferCommission: "19 ₽ за платёж",
		cashWithdrawalCommission: "0.5%",
		freeTransfers: 100,
		features: [
			"100 бесплатных платежей",
			"VIP-поддержка",
			"Персональный менеджер",
			"Овердрафт",
		],
		requirements: ["Паспорт", "ИНН", "ОГРН", "Устав"],
	},
	// Сбербанк
	{
		id: "sber-start",
		bankId: "sber",
		bankName: "Сбербанк",
		bankLogo: "/sberbank-logo-green.jpg",
		name: "Лёгкий старт",
		price: 0,
		priceLabel: "Бесплатно",
		description: "Бесплатный тариф для начинающих предпринимателей",
		targetAudience: "ИП и самозанятые",
		operationsLimit: 5,
		transferCommission: "100 ₽ за платёж",
		cashWithdrawalCommission: "2%",
		freeTransfers: 0,
		features: ["Бесплатное открытие", "Мобильный банк", "Интеграция с 1С"],
		requirements: ["Паспорт", "ИНН"],
	},
	{
		id: "sber-business",
		bankId: "sber",
		bankName: "Сбербанк",
		bankLogo: "/sberbank-logo-green.jpg",
		name: "Бизнес старт",
		price: 990,
		priceLabel: "990 ₽/мес",
		description: "Оптимальный тариф для малого бизнеса",
		targetAudience: "ИП и ООО с оборотом до 1 000 000 ₽",
		operationsLimit: 30,
		transferCommission: "50 ₽ за платёж",
		cashWithdrawalCommission: "1.5%",
		freeTransfers: 10,
		features: [
			"10 бесплатных платежей",
			"Эквайринг со скидкой",
			"Бизнес-карта",
		],
		requirements: ["Паспорт", "ИНН", "ОГРН"],
	},
	// Альфа-Банк
	{
		id: "alfa-free",
		bankId: "alfa",
		bankName: "Альфа-Банк",
		bankLogo: "/alfa-bank-logo-red.jpg",
		name: "На старте",
		price: 0,
		priceLabel: "Бесплатно",
		description: "Бесплатное обслуживание для нового бизнеса",
		targetAudience: "ИП с оборотом до 300 000 ₽",
		operationsLimit: 10,
		transferCommission: "59 ₽ за платёж",
		cashWithdrawalCommission: "1.9%",
		freeTransfers: 5,
		features: [
			"5 бесплатных платежей",
			"Онлайн-открытие за 10 минут",
			"Мобильный банк",
		],
		requirements: ["Паспорт", "ИНН"],
		isRecommended: true,
		recommendationReason: "Быстрое открытие и удобное приложение",
	},
	{
		id: "alfa-optimal",
		bankId: "alfa",
		bankName: "Альфа-Банк",
		bankLogo: "/alfa-bank-logo-red.jpg",
		name: "Оптимальный",
		price: 1490,
		priceLabel: "1 490 ₽/мес",
		description: "Сбалансированный тариф для растущего бизнеса",
		targetAudience: "ИП и ООО с оборотом до 3 000 000 ₽",
		operationsLimit: 50,
		transferCommission: "35 ₽ за платёж",
		cashWithdrawalCommission: "1.3%",
		freeTransfers: 25,
		features: [
			"25 бесплатных платежей",
			"Кэшбэк на бизнес-расходы",
			"Бесплатная бизнес-карта",
		],
		requirements: ["Паспорт", "ИНН", "ОГРН"],
	},
	// Модульбанк
	{
		id: "modul-start",
		bankId: "modul",
		bankName: "Модульбанк",
		bankLogo: "/modulbank-logo-green.jpg",
		name: "Стартовый",
		price: 0,
		priceLabel: "Бесплатно",
		description: "Бесплатный счёт для микробизнеса",
		targetAudience: "ИП с редкими операциями",
		operationsLimit: 5,
		transferCommission: "90 ₽ за платёж",
		cashWithdrawalCommission: "2.5%",
		freeTransfers: 0,
		features: [
			"Бесплатное обслуживание",
			"Простой интерфейс",
			"Быстрое открытие",
		],
		requirements: ["Паспорт", "ИНН"],
	},
	{
		id: "modul-optimal",
		bankId: "modul",
		bankName: "Модульбанк",
		bankLogo: "/modulbank-logo-green.jpg",
		name: "Оптимальный",
		price: 690,
		priceLabel: "690 ₽/мес",
		description: "Выгодный тариф для активного ИП",
		targetAudience: "ИП с оборотом до 1 000 000 ₽",
		operationsLimit: 30,
		transferCommission: "19 ₽ за платёж",
		cashWithdrawalCommission: "1%",
		freeTransfers: 15,
		features: [
			"15 бесплатных платежей",
			"Сниженные комиссии",
			"Интеграция с бухгалтерией",
		],
		requirements: ["Паспорт", "ИНН"],
		isRecommended: true,
		recommendationReason: "Лучшее соотношение цены и возможностей",
	},
];

export const promotions: Promotion[] = [
	{
		id: "tinkoff-promo-1",
		bankId: "tinkoff",
		bankName: "Тинькофф Банк",
		bankLogo: "/tinkoff-bank-logo-yellow.jpg",
		title: '3 месяца бесплатно на тарифе "Продвинутый"',
		description:
			"Откройте счёт до конца месяца и получите 3 месяца бесплатного обслуживания",
		type: "free_service",
		expiresAt: "2026-02-28",
		link: "/banks/tinkoff",
	},
	{
		id: "alfa-promo-1",
		bankId: "alfa",
		bankName: "Альфа-Банк",
		bankLogo: "/alfa-bank-logo-red.jpg",
		title: "Кэшбэк 10% на топливо",
		description:
			"Повышенный кэшбэк на АЗС для новых клиентов в течение первого месяца",
		type: "cashback",
		expiresAt: "2026-01-31",
		link: "/banks/alfa",
	},
	{
		id: "modul-promo-1",
		bankId: "modul",
		bankName: "Модульбанк",
		bankLogo: "/modulbank-logo-green.jpg",
		title: "Бонус 5000 ₽ на счёт",
		description:
			"Получите бонус при открытии счёта и первом пополнении от 50 000 ₽",
		type: "bonus",
		link: "/banks/modul",
	},
	{
		id: "sber-promo-1",
		bankId: "sber",
		bankName: "Сбербанк",
		bankLogo: "/sberbank-logo-green.jpg",
		title: "Бесплатная бухгалтерия на 6 месяцев",
		description: "Подключите онлайн-бухгалтерию бесплатно при открытии счёта",
		type: "free_service",
		link: "/banks/sber",
	},
];

export const blogPosts: BlogPost[] = [
	{
		id: "1",
		slug: "kak-vybrat-rko-dlya-ip",
		title: "Как выбрать РКО для ИП в 2026 году",
		excerpt:
			"Подробный гайд по выбору расчётно-кассового обслуживания для индивидуальных предпринимателей: на что обратить внимание и как сэкономить.",
		content: "",
		image: "/business-banking-guide.jpg",
		category: "guides",
		publishedAt: "2026-01-15",
		readTime: 8,
		author: { name: "Анна Смирнова" },
	},
	{
		id: "2",
		slug: "sravnenie-tarify-2026",
		title: "Сравнение тарифов РКО топ-5 банков",
		excerpt:
			"Детальное сравнение условий расчётно-кассового обслуживания в крупнейших банках России.",
		content: "",
		image: "/bank-comparison-chart.jpg",
		category: "comparisons",
		publishedAt: "2026-01-10",
		readTime: 12,
		author: { name: "Михаил Петров" },
	},
	{
		id: "3",
		slug: "besplatnoe-rko-podvodnye-kamni",
		title: "Бесплатное РКО: подводные камни",
		excerpt:
			"Разбираемся, действительно ли бесплатные тарифы выгодны и какие скрытые комиссии могут вас ждать.",
		content: "",
		image: "/financial-analysis-workspace.png",
		category: "reviews",
		publishedAt: "2026-01-05",
		readTime: 6,
		author: { name: "Елена Козлова" },
	},
];

export const regions = [
	"Москва",
	"Санкт-Петербург",
	"Екатеринбург",
	"Новосибирск",
	"Казань",
	"Нижний Новгород",
	"Все регионы",
];
